# Generated by Django 4.2.4 on 2023-08-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='tags')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('abstract', models.CharField(max_length=1024, verbose_name='abstract')),
                ('body', models.TextField(verbose_name='content')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='published')),
                ('tags', models.ManyToManyField(related_name='tags', to='blog.tags')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
